name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: .github/workflows/build.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: XiaomiEsimLPA
          path: module
